"""empty message

Revision ID: 8feba95495eb
Revises: e98cee06b3e9
Create Date: 2023-03-13 20:37:34.589023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8feba95495eb'
down_revision = 'e98cee06b3e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kosten', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kostenarten_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('einheiten_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_kosten_einheit_id', type_='foreignkey')
        batch_op.drop_constraint('fk_kosten_kostenart_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_kosten_einheit_id', 'einheiten', ['einheiten_id'], ['id'])
        batch_op.create_foreign_key('fk_kosten_kostenart_id', 'kostenarten', ['kostenarten_id'], ['id'])
        batch_op.drop_column('einheit_id')
        batch_op.drop_column('kostenart_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kosten', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kostenart_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('einheit_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_kosten_kostenart_id', type_='foreignkey')
        batch_op.drop_constraint('fk_kosten_einheit_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_kosten_kostenart_id', 'kostenarten', ['kostenart_id'], ['id'])
        batch_op.create_foreign_key('fk_kosten_einheit_id', 'einheiten', ['einheit_id'], ['id'])
        batch_op.drop_column('einheiten_id')
        batch_op.drop_column('kostenarten_id')

    # ### end Alembic commands ###
