"""empty message

Revision ID: e98cee06b3e9
Revises: 
Create Date: 2023-03-13 19:33:38.351565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98cee06b3e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('einheiten', schema=None) as batch_op:
        batch_op.alter_column('bezeichnung',
               existing_type=sa.TEXT(length=5),
               type_=sa.String(length=25),
               existing_nullable=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=False)

    with op.batch_alter_table('einheiten', schema=None) as batch_op:
        batch_op.alter_column('bezeichnung',
               existing_type=sa.String(length=25),
               type_=sa.TEXT(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###
